# Generated by Django 4.1 on 2022-08-30 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbr3at', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoucement',
            name='charity_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annoucement', to=settings.AUTH_USER_MODEL),
        ),
    ]
