# Generated by Django 4.1 on 2022-08-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbr3at', '0003_alter_charity_description_alter_charity_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='numOfDonation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
