# Generated by Django 4.1 on 2022-08-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbr3at', '0004_userprofile_numofdonation_userprofile_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numOfDonation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
